source 'https://rubygems.org'

gem 'rake'
gem 'sinatra'
gem 'github-pages', '>= 73'
gem 'jekyll'
gem 'github-markdown'
gem 'dotenv'
gem 'thin'
gem 'haml'
gem 'foreman'
gem 'mongoid', '~> 5.1', '>= 5.1.2'
gem 'rack-conneg'
gem 'rack-cors', :require => 'rack/cors'
gem 'iso8601'
gem 'exception_notification', '>= 4.1.1'
gem 'compass'
gem 'bootstrap-sass', '>= 3.3.6'
gem 'pusher'

group :test do
  gem 'capybara-webkit', '>= 1.5.2'
  gem 'cucumber', "~> 1.3"
  gem 'cucumber-sinatra'
  gem 'rspec'
  gem 'rack-test'
  gem 'guard'
  gem 'guard-rspec', require: false
  gem 'guard-jasmine'
  gem 'guard-cucumber'
  gem 'terminal-notifier-guard'
  gem 'coveralls', '>= 0.8.14', require: false
  gem 'cucumber-api-steps', require: false, github: 'theodi/cucumber-api-steps', branch: 'feature-test-content-type'
  gem 'database_cleaner'
  gem 'guard-shotgun', :git => 'https://github.com/rchampourlier/guard-shotgun.git'
  gem 'jasmine'
  gem 'timecop'
  gem 'data_kitten', '>= 1.3.1'
  gem 'webmock'
end
