source 'https://rubygems.org'

gem 'rake'
gem 'sinatra'
gem 'github-pages', '>= 73'
gem 'jekyll', '>= 3.0.4'
gem 'github-markdown'
gem 'dotenv'
gem 'thin'
gem 'haml'
gem 'foreman'
gem 'mongoid', '~> 5.0'
gem 'rack-conneg'
gem 'rack-cors', :require => 'rack/cors'
gem 'iso8601'
gem 'exception_notification'
gem 'compass', '>= 1.0.3'
gem 'bootstrap-sass'
gem 'pusher'

group :test do
  gem 'capybara-webkit'
  gem 'cucumber', "~> 1.3"
  gem 'cucumber-sinatra'
  gem 'rspec'
  gem 'rack-test'
  gem 'guard', '>= 2.12.6'
  gem 'guard-rspec', '>= 4.5.2', require: false
  gem 'guard-jasmine', '>= 2.0.6'
  gem 'guard-cucumber'
  gem 'terminal-notifier-guard'
  gem 'coveralls', require: false
  gem 'cucumber-api-steps', require: false, github: 'theodi/cucumber-api-steps', branch: 'feature-test-content-type'
  gem 'database_cleaner'
  gem 'guard-shotgun', :git => 'https://github.com/rchampourlier/guard-shotgun.git'
  gem 'jasmine'
  gem 'timecop'
  gem 'data_kitten'
  gem 'webmock'
end
